# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Publications"
  url = "#publications"
  weight = 20

[[main]]
  name = "Blog"
  url = "#the-platonic-realm"
  weight = 30

[[main]]
  name = "Shots In The Quark"
  url = "#shots-in-the-quark"
  weight = 40

[[main]]
  name = "Physically Debunked"
  url = "#physically-debunked"
  weight = 50

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/media/resume.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "media/resume.pdf"
#    weight = 70
